CREATE TABLE category (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE
);

CREATE TABLE items (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE,
    category_id BIGINT NOT NULL DEFAULT 1 REFERENCES category(id)
);

CREATE TABLE users (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE locations (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_by BIGINT NOT NULL REFERENCES users(id),
    cover VARCHAR(255)
);

CREATE TABLE exist_items (
    exist_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    item_id INT REFERENCES items(id),
    location_id INT REFERENCES locations(id),
    quantity INT NOT NULL DEFAULT 1,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(location_id, item_id)
);

CREATE TABLE need_items (
    need_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    item_id INT REFERENCES items(id),
    location_id INT REFERENCES locations(id),
    quantity INT NOT NULL DEFAULT 1,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(location_id, item_id)
);

CREATE TABLE user_session (
    id TEXT NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    expires_at TIMESTAMPTZ NOT NULL
);
